VERITAS-Observatory/Eventdisplay_AnalysisScripts_VTS

scripts/IRF.combine_effective_area_parts.sh
scripts/IRF.combine_lookup_table_parts.sh
scripts/IRF.production.sh
scripts/helper_scripts/ANALYSIS.evndisp_laser_sub.sh
scripts/helper_scripts/IRF.effective_area_combine_sub.sh
scripts/helper_scripts/IRF.lookup_table_combine_sub.sh

Introduce options in combineEffectiveAreas and combineLookupTables to reduce file IRF file sizes.
See Eventdisplay pull request https://github.com/VERITAS-Observatory/EventDisplay_v4/pull/149

Options for reduced IRF file size

---

scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/IRF.compress_evndisp_MC.sh
scripts/IRF.generate_lookup_table_parts.sh
scripts/IRF.production.sh
scripts/helper_scripts/IRF.compress_evndisp_MC_sub.sh
scripts/helper_scripts/IRF.generate_mscw_effective_area_parts_sub.sh
scripts/helper_scripts/IRF.lookup_table_parallel_sub.sh
scripts/helper_scripts/IRF.mscw_energy_MC_sub.sh
scripts/submissionCommands.dat

This release includes:
- add functionality to compress evndisp stage simulation files (including log files)
- allow evndisp files for mscw stages to be zstd compressed.
- bug fix in handling V2DL3 scripts in anasum

v487d scripts development

---

scripts/IRF.compress_evndisp_MC.sh
scripts/IRF.evndisp_MC.sh
scripts/IRF.generate_mscw_effective_area_parts.sh
scripts/IRF.mscw_energy_MC.sh
scripts/RUNLIST.whichRunsAreAtmosphere.sh

Changes relative to v490-alpha.4
- remove OBS_ENV variables and replace by VERITAS_ENV variables
- add 61/62 atmosphere IDs to RUNLIST.whichRunsAreAtmosphere.sh

v490-alpha.5

---

scripts/IRF.generalproduction.sh
scripts/IRF.production.sh
scripts/IRF.trainTMVAforGammaHadronSeparation.sh
scripts/helper_scripts/IRF.trainTMVAforGammaHadronSeparation_sub.sh

Changes with respect to alpha.9:
- improvements of TMVA gamma/hadron separation training

v490-alpha.10 - TMVA training and testing

---

scripts/ANALYSIS.anasum_parallel.sh
scripts/ANALYSIS.evndisp.sh
scripts/ANALYSIS.evndisp_laser.sh
scripts/ANALYSIS.evndisp_muon.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/IRF.combine_effective_area_parts.sh
scripts/IRF.generate_lookup_table_parts.sh
scripts/IRF.generate_radial_acceptance.sh
scripts/IRF.mscw_energy_MC.sh
scripts/IRF.trainTMVAforAngularReconstruction.sh
scripts/IRF.trainTMVAforGammaHadronSeparation.sh
scripts/SPANALYSIS.lowgainped.sh
scripts/SPANALYSIS.make_DST.sh
scripts/submissionCommands.dat

I haven't been able to test all of the IRF and training scripts but the analysis scripts work. It should working for anything that would be submitted under pbs as "qsub script.sh". Like under qsub, $SUBC will contain the default options for when submitting with sbatch. I've added the McGill example in submissionCommands.dat.

Slurm submission

---

scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/IRF.mscw_energy_MC.sh
scripts/IRF.production.sh
scripts/helper_scripts/IRF.generate_mscw_effective_area_parts_sub.sh
scripts/helper_scripts/IRF.mscw_energy_MC_sub.sh

Add possibility to analysis data and simulations with v487 using these scripts. Requires for DESY users, as the old scripts are not adapted to HTCondor.

v490 - integration of v487 running

---

scripts/ANALYSIS.anasum_combine.sh
scripts/ANALYSIS.anasum_parallel.sh
scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/IRF.evndisp_MC.sh
scripts/IRF.generate_effective_area_parts.sh
scripts/IRF.production.sh
scripts/IRF.selectRunsForBDTTraining.sh
scripts/helper_scripts/ANALYSIS.anasum_combine_sub.sh
scripts/helper_scripts/ANALYSIS.anasum_sub.sh
scripts/helper_scripts/ANALYSIS.evndisp_sub.sh
scripts/helper_scripts/ANALYSIS.mscw_energy_sub.sh
scripts/helper_scripts/IRF.effective_area_combine_sub.sh
scripts/helper_scripts/IRF.lookup_table_combine_sub.sh
scripts/helper_scripts/IRF.lookup_table_parallel_sub.sh
scripts/helper_scripts/IRF.optimizeTMVAforGammaHadronSeparation_sub.sh
scripts/helper_scripts/IRF.radial_acceptance_sub.sh
scripts/helper_scripts/IRF.trainTMVAforGammaHadronSeparation_sub.sh

This PR includes improvements relative to alpha.12:
- significant improvements in job submission rate, especially for anasum
- log files are always written into root files now (using the `logFile` mechanism)
- `ANALYSIS.anasum_combine.sh` is submitted to farm
- add script to optimise BDT cuts
- clean up and consistent usage of environmental variables
-

v490 - alpha.13 - efficiency improvements

---

scripts/ANALYSIS.anasum_combine.sh
scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.evndisp.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/IRF.generalproduction.sh
scripts/IRF.mscw_energy_MC.sh
scripts/IRF.optimizeTMVAforGammaHadronSeparation.sh
scripts/IRF.production.sh
scripts/IRF.selectRunsForBDTTraining.sh
scripts/IRF.trainTMVAforGammaHadronSeparation.sh
scripts/UTILITY.sortRunsInSubDirectories.sh
scripts/helper_scripts/ANALYSIS.anasum_sub.sh
scripts/helper_scripts/IRF.evndisp_MC_sub.sh
scripts/helper_scripts/IRF.mscw_energy_MC_sub.sh
scripts/helper_scripts/IRF.optimizeTMVAforGammaHadronSeparation_sub.sh
scripts/helper_scripts/submit_scripts_to_htcondor.sh

This PR includes changes with respect to v490 - alpha.13:
- evndisp/mscw analysis directories can now be organized in subdirectories with the name of the leading digits of the run number
- improvement for redHV processing
- efficiency improvements for processing of large number of runs

v490 - alpha.14 - redHV processing; bug fixes

---

README.md
scripts/ANALYSIS.anasum.sh
scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.evndisp.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/ANALYSIS.v2dl3.sh

This PR includes:
- fix to anasum script (issue #66)
- removal of outdated cut option for NN
- improved documentation on VERITAS_ANALYSIS_TYPE
- ...

v490.3 - dev1 bug fixes;

---

scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.v2dl3.sh
scripts/db_scripts/README.md
scripts/db_scripts/db_L3.sh
scripts/db_scripts/db_fir.sh
scripts/db_scripts/db_pack_new_directories.sh
scripts/db_scripts/db_rawpointing.sh
scripts/db_scripts/db_run.sh
scripts/db_scripts/db_weather.sh
scripts/helper_scripts/ANALYSIS.v2dl3_sub.sh
scripts/preprocessing/archive_error_files.sh

Script improvements for the pre-processing of anasum and v2dl3 stages:
- add run script to analyse a large amount of files with V2DL3 (submits batches of 100 files to a computer farm)
- add additional scripts in preparation of adding DQM info to DL3 obs tables.

v490.3 dev2 - anasum and v2dl3 preprocessing

---

scripts/db_scripts/db_lidar.sh
scripts/db_scripts/db_run.sh
scripts/db_scripts/db_update_tar_balls.sh

(wrong branch name)
Add lidar support; improved downloading; updating of tar balls.

v490.3 dev4

---

.pre-commit-config.yaml
scripts/ANALYSIS.v2dl3.sh
scripts/db_scripts/README.md
scripts/db_scripts/db_combine_dqm_fits.py
scripts/db_scripts/db_rundqm.sh
scripts/db_scripts/db_write_fits.py
scripts/db_scripts/environment.yml
scripts/helper_scripts/ANALYSIS.v2dl3_sub.sh

This will be used for DQM to add additional information to obs table.
Added also to the V2DL3 analysis script:
- DB fits file flag to fill this into DL3 files
- WRITE-ALL-EVENTS is assumed to be standard and write full enclosure also for this case.

Adds a small script to write DB tables into a fits file; summary of DQM for DL3

---

scripts/ANALYSIS.anasum_link_files.sh
scripts/ARCHIVE.prepare_download_from_DESY.sh
scripts/ARCHIVE.prepare_download_from_UCLA.sh
scripts/IRF.generalproduction.sh
scripts/IRF.production.sh
scripts/helper_scripts/ANALYSIS.anasum_sub.sh
scripts/helper_scripts/ANALYSIS.mscw_energy_sub.sh
scripts/helper_scripts/IRF.generate_mscw_effective_area_parts_sub.sh
scripts/helper_scripts/IRF.mscw_energy_MC_sub.sh

This pull request includes:
- improved handling of UV filter simulation processing
- improved anasum processing with pre-processed files
- additions to downloading scripts for DL3 files.

v490 - Improved anasum processing with pre-processed files

---

scripts/ANALYSIS.v2dl3.sh
scripts/SPANALYSIS.evndisp_laser_run.sh
scripts/db_scripts/db_write_fits_from_runlist.sh
scripts/db_scripts/query_run_list.sh
scripts/preprocessing/README.md

This PR includes:
- improved docs and readmes.
- add pixel selection info for laser analysis

v490.4 dev1 - improved docs and printouts

---

scripts/db_scripts/db_camerarotation.sh

Change readout of camera readout so that values are sorted by version (newest version on the top).

V490.6 dev2 camera rotation readout

---

README.md
scripts/ANALYSIS.anasum_allcuts.sh
scripts/ANALYSIS.anasum_combine.sh
scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.evndisp.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/helper_scripts/ANALYSIS.anasum_combine_sub.sh
scripts/helper_scripts/ANALYSIS.anasum_sub.sh
scripts/helper_scripts/ANALYSIS.evndisp_sub.sh
scripts/helper_scripts/ANALYSIS.mscw_energy_sub.sh
scripts/helper_scripts/ANALYSIS.v2dl3_sub.sh
scripts/helper_scripts/submit_scripts_to_htcondor.sh
scripts/preprocessing/processing_dqm.sh
scripts/set_v490_apptainer.sh

This PR includes significant changes to allow for the use of apptainers for the VERITAS data analysis. This is implemented only for the analysis script of observational data, not for the scripts used for the IRF production.

v490.7 preprocessing dev1 - efficiency improvments / apptainers

---

scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.evndisp.sh
scripts/ANALYSIS.mscw_energy.sh
scripts/IRF.generalproduction.sh
scripts/IRF.production.sh
scripts/helper_scripts/submit_scripts_to_htcondor.sh
scripts/submissionCommands.dat

v490.7 Add hard2tel options.

---

scripts/ANALYSIS.anasum_allcuts.sh
scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/ANALYSIS.v2dl3.sh
scripts/helper_scripts/ANALYSIS.anasum_combine_sub.sh
scripts/helper_scripts/ANALYSIS.v2dl3_sub.sh

This PR includes:
- addition of printing sensitivity from Crab measurements
- V2DL3 conversion improvements and simplifications (no evndisp tools necessary anymore)

v490.7 preprocessing dev3 v2dl3 processing

---

scripts/IRF.evndisp_MC.sh

Massive memory increase for MC; need to understand what is happening.

v490.9-dev 1 - script improvements.

---

scripts/ANALYSIS.anasum_allcuts.sh
scripts/IRF.generalproduction.sh
scripts/IRF.production.sh
scripts/RUNLIST.preprocessing.sh
scripts/helper_scripts/ANALYSIS.v2dl3_sub.sh
scripts/helper_scripts/submit_scripts_to_htcondor.sh
scripts/set_environment.sh

Following improvements:
- `helper_scripts/submit_scripts_to_htcondor.sh` did not work for a large number of fils to be submitted

v490.9 dev5 - script submission improvements

---

scripts/ANALYSIS.anasum_parallel_from_runlist.sh
scripts/db_scripts/db_L3.sh
scripts/db_scripts/db_VPM.sh
scripts/db_scripts/db_lidar.sh
scripts/db_scripts/db_rawpointing.sh

- Improve robustness for cut file search
- improved handling of zero entries in DB

v492.0 dev2
